version: "3.8"
services:
  localstack-sg:
    container_name: localstack-sg
    image: localstack/localstack-pro
    ports:
      - "4566:4566"
    environment:
      - SERVICES=cloudfront,wafv2,route53,s3,elbv2,ec2,rds,iam,sts,autoscaling,cloudwatch,dynamodb,secretsmanager,ssm,cloudcontrol
      - REGION=ap-southeast-1
      - LOCALSTACK_AUTH_TOKEN=ls-LIFOXIMi-5005-daDo-RuHo-2591lEQE764f
      - DEBUG=1
      - PERSISTENCE=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EDGE_PORT=4566
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - "${PWD}/volume/sg:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 3

  localstack-th:
    container_name: localstack-th
    image: localstack/localstack-pro
    ports:
      - "4567:4566"
    environment:
      - SERVICES=cloudfront,wafv2,route53,s3,elbv2,ec2,rds,iam,sts,autoscaling,cloudwatch,dynamodb,secretsmanager,ssm,cloudcontrol
      - REGION=ap-southeast-2
      - LOCALSTACK_AUTH_TOKEN=ls-LIFOXIMi-5005-daDo-RuHo-2591lEQE764f
      - DEBUG=1
      - PERSISTENCE=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EDGE_PORT=4567
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - "${PWD}/volume/th:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4567/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 3
